-- MySQL Script generated by MySQL Workbench
-- Wed Jul 18 13:55:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema azulProduccion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema azulProduccion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `azulProduccion` DEFAULT CHARACTER SET utf8 ;
USE `azulProduccion` ;

-- -----------------------------------------------------
-- Table `azulProduccion`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(255) NOT NULL,
  `apellido_usuario` VARCHAR(255) NOT NULL,
  `correo_usuario` VARCHAR(255) NOT NULL,
  `nivel_usuario` INT NOT NULL,
  `fecha_registro` DATE NOT NULL,
  `telefono_usuario` VARCHAR(12) NOT NULL,
  `pass_usuario` TEXT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`carrito` (
  `id_carrito` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_carrito`, `usuario_id_usuario`),
  INDEX `fk_carrito_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_carrito_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `azulProduccion`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`domicilio` (
  `id_domicilio` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(255) NOT NULL,
  `codigo_postal` VARCHAR(255) NOT NULL,
  `municipio` VARCHAR(255) NOT NULL,
  `colonia` VARCHAR(255) NOT NULL,
  `no_interior` INT NULL,
  `no_exterior` INT NULL,
  `localidad` VARCHAR(255) NOT NULL,
  `calle` VARCHAR(255) NOT NULL,
  `referencias` TEXT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_domicilio`, `usuario_id_usuario`),
  INDEX `fk_domicilio_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_domicilio_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `azulProduccion`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`costos_de_envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`costos_de_envio` (
  `id_costo` INT NOT NULL AUTO_INCREMENT,
  `costo` INT NOT NULL,
  PRIMARY KEY (`id_costo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`compras` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `carrito_id_carrito` INT NOT NULL,
  `domicilio_id_domicilio` INT NOT NULL,
  `costos_de_envio_id_costo` INT NOT NULL,
  PRIMARY KEY (`id_compra`, `carrito_id_carrito`, `domicilio_id_domicilio`, `costos_de_envio_id_costo`),
  INDEX `fk_compras_carrito1_idx` (`carrito_id_carrito` ASC),
  INDEX `fk_compras_domicilio1_idx` (`domicilio_id_domicilio` ASC),
  INDEX `fk_compras_costos_de_envio1_idx` (`costos_de_envio_id_costo` ASC),
  CONSTRAINT `fk_compras_carrito1`
    FOREIGN KEY (`carrito_id_carrito`)
    REFERENCES `azulProduccion`.`carrito` (`id_carrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_domicilio1`
    FOREIGN KEY (`domicilio_id_domicilio`)
    REFERENCES `azulProduccion`.`domicilio` (`id_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_costos_de_envio1`
    FOREIGN KEY (`costos_de_envio_id_costo`)
    REFERENCES `azulProduccion`.`costos_de_envio` (`id_costo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`entradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`entradas` (
  `id_entrada` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `titulo_entrada` VARCHAR(255) NOT NULL,
  `url_entrada` VARCHAR(255) NOT NULL,
  `cuerpo_entrada` TEXT NOT NULL,
  `fecha_entrada` DATE NOT NULL,
  PRIMARY KEY (`id_entrada`, `usuario_id_usuario`),
  INDEX `fk_entradas_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_entradas_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `azulProduccion`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`evento` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `nombre_evento` VARCHAR(255) NOT NULL,
  `precio_evento` DOUBLE NOT NULL,
  `domicilio_id_domicilio` INT NOT NULL,
  PRIMARY KEY (`id_evento`, `domicilio_id_domicilio`),
  INDEX `fk_evento_domicilio1_idx` (`domicilio_id_domicilio` ASC),
  CONSTRAINT `fk_evento_domicilio1`
    FOREIGN KEY (`domicilio_id_domicilio`)
    REFERENCES `azulProduccion`.`domicilio` (`id_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`categoria_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`categoria_producto` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(255) NOT NULL,
  `descripcion_producto` VARCHAR(255) NOT NULL,
  `precio_producto` INT NOT NULL,
  `keyword_producto` VARCHAR(255) NOT NULL,
  `categoria_producto_id_categoria` INT NOT NULL,
  `stock` INT NOT NULL,
  `codigo_interno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_producto`, `categoria_producto_id_categoria`),
  INDEX `fk_productos_categoria_producto1_idx` (`categoria_producto_id_categoria` ASC),
  CONSTRAINT `fk_productos_categoria_producto1`
    FOREIGN KEY (`categoria_producto_id_categoria`)
    REFERENCES `azulProduccion`.`categoria_producto` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`promociones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`promociones` (
  `id_promociones` INT NOT NULL AUTO_INCREMENT,
  `nombre_promocion` VARCHAR(255) NOT NULL,
  `porcentaje_promocion` INT NOT NULL,
  PRIMARY KEY (`id_promociones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`productos_con_promociones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`productos_con_promociones` (
  `productos_id_producto` INT NOT NULL,
  `promociones_id_promociones` INT NOT NULL,
  PRIMARY KEY (`productos_id_producto`, `promociones_id_promociones`),
  INDEX `fk_productos_has_promociones_promociones1_idx` (`promociones_id_promociones` ASC),
  INDEX `fk_productos_has_promociones_productos1_idx` (`productos_id_producto` ASC),
  CONSTRAINT `fk_productos_has_promociones_productos1`
    FOREIGN KEY (`productos_id_producto`)
    REFERENCES `azulProduccion`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_has_promociones_promociones1`
    FOREIGN KEY (`promociones_id_promociones`)
    REFERENCES `azulProduccion`.`promociones` (`id_promociones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`productos_en_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`productos_en_carrito` (
  `productos_id_producto` INT NOT NULL,
  `cantidad_producto` INT NOT NULL,
  `carrito_id_carrito` INT NOT NULL,
  PRIMARY KEY (`productos_id_producto`, `carrito_id_carrito`),
  INDEX `fk_carrito_has_productos_productos1_idx` (`productos_id_producto` ASC),
  INDEX `fk_productos_en_carrito_carrito1_idx` (`carrito_id_carrito` ASC),
  CONSTRAINT `fk_carrito_has_productos_productos1`
    FOREIGN KEY (`productos_id_producto`)
    REFERENCES `azulProduccion`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_en_carrito_carrito1`
    FOREIGN KEY (`carrito_id_carrito`)
    REFERENCES `azulProduccion`.`carrito` (`id_carrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`factura` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `compras_id_compra` INT NOT NULL,
  `rfc_factura` VARCHAR(255) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `domicilio_id_domicilio` INT NOT NULL,
  PRIMARY KEY (`id_factura`, `compras_id_compra`, `usuario_id_usuario`),
  INDEX `fk_factura_compras1_idx` (`compras_id_compra` ASC),
  INDEX `fk_factura_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_factura_domicilio1_idx` (`domicilio_id_domicilio` ASC),
  CONSTRAINT `fk_factura_compras1`
    FOREIGN KEY (`compras_id_compra`)
    REFERENCES `azulProduccion`.`compras` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `azulProduccion`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_domicilio1`
    FOREIGN KEY (`domicilio_id_domicilio`)
    REFERENCES `azulProduccion`.`domicilio` (`id_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`evento_en_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`evento_en_carrito` (
  `carrito_id_carrito` INT NOT NULL,
  `evento_id_evento` INT NOT NULL,
  PRIMARY KEY (`carrito_id_carrito`, `evento_id_evento`),
  INDEX `fk_evento_en_carrito_evento1_idx` (`evento_id_evento` ASC),
  CONSTRAINT `fk_evento_en_carrito_carrito1`
    FOREIGN KEY (`carrito_id_carrito`)
    REFERENCES `azulProduccion`.`carrito` (`id_carrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_en_carrito_evento1`
    FOREIGN KEY (`evento_id_evento`)
    REFERENCES `azulProduccion`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `azulProduccion`.`productos_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`productos_compra` (
  `productos_id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `compras_id_compra` INT NOT NULL,
  PRIMARY KEY (`productos_id_producto`, `compras_id_compra`),
  INDEX `fk_eventos_compra_compras1_idx` (`compras_id_compra` ASC),
  CONSTRAINT `fk_eventos_compra_productos1`
    FOREIGN KEY (`productos_id_producto`)
    REFERENCES `azulProduccion`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_compra_compras1`
    FOREIGN KEY (`compras_id_compra`)
    REFERENCES `azulProduccion`.`compras` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`eventos_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`eventos_compra` (
  `evento_id_evento` INT NOT NULL,
  `compras_id_compra` INT NOT NULL,
  PRIMARY KEY (`evento_id_evento`, `compras_id_compra`),
  INDEX `fk_eventos_compra_compras2_idx` (`compras_id_compra` ASC),
  CONSTRAINT `fk_eventos_compra_evento1`
    FOREIGN KEY (`evento_id_evento`)
    REFERENCES `azulProduccion`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_compra_compras2`
    FOREIGN KEY (`compras_id_compra`)
    REFERENCES `azulProduccion`.`compras` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`recuperar_clave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`recuperar_clave` (
  `usuario_id_usuario` INT NOT NULL,
  `url_secreta` TEXT NOT NULL,
  `id_recuperar_clave` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`, `id_recuperar_clave`),
  UNIQUE INDEX `id_recuperar_clave_UNIQUE` (`id_recuperar_clave` ASC),
  CONSTRAINT `fk_recuperar_clave_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `azulProduccion`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `azulProduccion`.`autenticar_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `azulProduccion`.`autenticar_user` (
  `id_autenticacion` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `url_autenticar` TEXT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`, `id_autenticacion`),
  UNIQUE INDEX `id_autenticacion_UNIQUE` (`id_autenticacion` ASC),
  CONSTRAINT `fk_autenticar_user_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `azulProduccion`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
