-- MySQL Script generated by MySQL Workbench
-- Mon Jun  4 14:00:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(255) NOT NULL,
  `apellido_usuario` VARCHAR(255) NOT NULL,
  `correo_usuario` VARCHAR(255) NOT NULL,
  `nivel_usuario` INT NOT NULL,
  `fecha_registro` DATE NOT NULL,
  `telefono_usuario` VARCHAR(12) NOT NULL,
  `pass_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrito` (
  `id_carrito` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_carrito`, `usuario_id_usuario`),
  INDEX `fk_carrito_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_carrito_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`codigo_postal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`codigo_postal` (
  `id_codigo` INT NOT NULL AUTO_INCREMENT,
  `estado_id_estado` INT NOT NULL,
  `codigo_postal` INT NOT NULL,
  PRIMARY KEY (`id_codigo`, `estado_id_estado`),
  INDEX `fk_codigo_postal_estado1_idx` (`estado_id_estado` ASC),
  CONSTRAINT `fk_codigo_postal_estado1`
    FOREIGN KEY (`estado_id_estado`)
    REFERENCES `mydb`.`estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`municipio` (
  `id_municipio` INT NOT NULL AUTO_INCREMENT,
  `estado_id_estado` INT NOT NULL,
  `nombre_municipio` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_municipio`, `estado_id_estado`),
  INDEX `fk_municipio_estado1_idx` (`estado_id_estado` ASC),
  CONSTRAINT `fk_municipio_estado1`
    FOREIGN KEY (`estado_id_estado`)
    REFERENCES `mydb`.`estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`domicilio` (
  `id_domicilio` INT NOT NULL,
  `estado_id_estado` INT NOT NULL,
  `codigo_postal_id_codigo` INT NOT NULL,
  `municipio_id_municipio` INT NOT NULL,
  `colonia` INT NOT NULL,
  `no_interior` INT NULL,
  `no_exterior` INT NULL,
  `localidad` VARCHAR(255) NOT NULL,
  `calle` VARCHAR(255) NOT NULL,
  `referencias` TEXT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_domicilio`, `estado_id_estado`, `codigo_postal_id_codigo`, `municipio_id_municipio`, `usuario_id_usuario`),
  INDEX `fk_domicilio_estado1_idx` (`estado_id_estado` ASC),
  INDEX `fk_domicilio_codigo_postal1_idx` (`codigo_postal_id_codigo` ASC),
  INDEX `fk_domicilio_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_domicilio_municipio1_idx` (`municipio_id_municipio` ASC),
  CONSTRAINT `fk_domicilio_estado1`
    FOREIGN KEY (`estado_id_estado`)
    REFERENCES `mydb`.`estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domicilio_codigo_postal1`
    FOREIGN KEY (`codigo_postal_id_codigo`)
    REFERENCES `mydb`.`codigo_postal` (`id_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domicilio_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domicilio_municipio1`
    FOREIGN KEY (`municipio_id_municipio`)
    REFERENCES `mydb`.`municipio` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compras` (
  `id_compra` INT NOT NULL,
  `carrito_id_carrito` INT NOT NULL,
  `domicilio_id_domicilio` INT NOT NULL,
  PRIMARY KEY (`id_compra`, `carrito_id_carrito`, `domicilio_id_domicilio`),
  INDEX `fk_compras_carrito1_idx` (`carrito_id_carrito` ASC),
  INDEX `fk_compras_domicilio1_idx` (`domicilio_id_domicilio` ASC),
  CONSTRAINT `fk_compras_carrito1`
    FOREIGN KEY (`carrito_id_carrito`)
    REFERENCES `mydb`.`carrito` (`id_carrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_domicilio1`
    FOREIGN KEY (`domicilio_id_domicilio`)
    REFERENCES `mydb`.`domicilio` (`id_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entradas` (
  `id_entrada` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `titulo_entrada` VARCHAR(255) NOT NULL,
  `url_entrada` VARCHAR(255) NOT NULL,
  `cuerpo_entrada` TEXT NOT NULL,
  `fecha_entrada` DATE NOT NULL,
  PRIMARY KEY (`id_entrada`, `usuario_id_usuario`),
  INDEX `fk_entradas_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_entradas_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento` (
  `id_evento` INT NOT NULL,
  `nombre_evento` VARCHAR(255) NOT NULL,
  `precio_evento` DOUBLE NOT NULL,
  PRIMARY KEY (`id_evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria_producto` (
  `id_categoria` INT NOT NULL,
  `nombre_categoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `id_producto` INT NOT NULL,
  `nombre_producto` VARCHAR(255) NOT NULL,
  `descripcion_producto` VARCHAR(255) NOT NULL,
  `precio_producto` INT NOT NULL,
  `keyword_producto` VARCHAR(255) NOT NULL,
  `categoria_producto_id_categoria` INT NOT NULL,
  `stock` INT NOT NULL,
  `codigo_interno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_producto`, `categoria_producto_id_categoria`),
  INDEX `fk_productos_categoria_producto1_idx` (`categoria_producto_id_categoria` ASC),
  CONSTRAINT `fk_productos_categoria_producto1`
    FOREIGN KEY (`categoria_producto_id_categoria`)
    REFERENCES `mydb`.`categoria_producto` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`promociones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`promociones` (
  `id_promociones` INT NOT NULL,
  `nombre_promocion` VARCHAR(255) NOT NULL,
  `porcentaje_promocion` INT NOT NULL,
  PRIMARY KEY (`id_promociones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos_con_promociones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos_con_promociones` (
  `productos_id_producto` INT NOT NULL,
  `promociones_id_promociones` INT NOT NULL,
  PRIMARY KEY (`productos_id_producto`, `promociones_id_promociones`),
  INDEX `fk_productos_has_promociones_promociones1_idx` (`promociones_id_promociones` ASC),
  INDEX `fk_productos_has_promociones_productos1_idx` (`productos_id_producto` ASC),
  CONSTRAINT `fk_productos_has_promociones_productos1`
    FOREIGN KEY (`productos_id_producto`)
    REFERENCES `mydb`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_has_promociones_promociones1`
    FOREIGN KEY (`promociones_id_promociones`)
    REFERENCES `mydb`.`promociones` (`id_promociones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos_en_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos_en_carrito` (
  `productos_id_producto` INT NOT NULL,
  `cantidad_producto` INT NOT NULL,
  `carrito_id_carrito` INT NOT NULL,
  PRIMARY KEY (`productos_id_producto`, `carrito_id_carrito`),
  INDEX `fk_carrito_has_productos_productos1_idx` (`productos_id_producto` ASC),
  INDEX `fk_productos_en_carrito_carrito1_idx` (`carrito_id_carrito` ASC),
  CONSTRAINT `fk_carrito_has_productos_productos1`
    FOREIGN KEY (`productos_id_producto`)
    REFERENCES `mydb`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_en_carrito_carrito1`
    FOREIGN KEY (`carrito_id_carrito`)
    REFERENCES `mydb`.`carrito` (`id_carrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_has_domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_has_domicilio` (
  `usuario_id_usuario` INT NOT NULL,
  `usuario_carrito_id_carrito` INT NOT NULL,
  `usuario_domicilio_id_domicilio` INT NOT NULL,
  `usuario_domicilio_eventos_id_evento` INT NOT NULL,
  `usuario_domicilio_eventos_participantesEvento_id_participante` INT NOT NULL,
  `usuario_eventos_id_evento` INT NOT NULL,
  `usuario_eventos_participantesEvento_id_participante` INT NOT NULL,
  `usuario_eventos_participante_evento_id_participante` INT NOT NULL,
  `domicilio_id_domicilio` INT NOT NULL,
  `domicilio_eventos_id_evento` INT NOT NULL,
  `domicilio_eventos_participantesEvento_id_participante` INT NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`, `usuario_carrito_id_carrito`, `usuario_domicilio_id_domicilio`, `usuario_domicilio_eventos_id_evento`, `usuario_domicilio_eventos_participantesEvento_id_participante`, `usuario_eventos_id_evento`, `usuario_eventos_participantesEvento_id_participante`, `usuario_eventos_participante_evento_id_participante`, `domicilio_id_domicilio`, `domicilio_eventos_id_evento`, `domicilio_eventos_participantesEvento_id_participante`),
  INDEX `fk_usuario_has_domicilio_domicilio1_idx` (`domicilio_id_domicilio` ASC, `domicilio_eventos_id_evento` ASC, `domicilio_eventos_participantesEvento_id_participante` ASC),
  INDEX `fk_usuario_has_domicilio_usuario1_idx` (`usuario_id_usuario` ASC, `usuario_carrito_id_carrito` ASC, `usuario_domicilio_id_domicilio` ASC, `usuario_domicilio_eventos_id_evento` ASC, `usuario_domicilio_eventos_participantesEvento_id_participante` ASC, `usuario_eventos_id_evento` ASC, `usuario_eventos_participantesEvento_id_participante` ASC, `usuario_eventos_participante_evento_id_participante` ASC),
  CONSTRAINT `fk_usuario_has_domicilio_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_domicilio_domicilio1`
    FOREIGN KEY (`domicilio_id_domicilio`)
    REFERENCES `mydb`.`domicilio` (`id_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`domicilio_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`domicilio_evento` (
  `id_domicilio_evento` INT NOT NULL AUTO_INCREMENT,
  `eventos_id_evento` INT NOT NULL,
  `domicilio_id_domicilio` INT NOT NULL,
  PRIMARY KEY (`id_domicilio_evento`, `eventos_id_evento`, `domicilio_id_domicilio`),
  INDEX `fk_domicilio_evento_domicilio1_idx` (`domicilio_id_domicilio` ASC),
  CONSTRAINT `fk_domicilio_evento_eventos1`
    FOREIGN KEY (`eventos_id_evento`)
    REFERENCES `mydb`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domicilio_evento_domicilio1`
    FOREIGN KEY (`domicilio_id_domicilio`)
    REFERENCES `mydb`.`domicilio` (`id_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`factura` (
  `id_factura` INT NOT NULL,
  `compras_id_compra` INT NOT NULL,
  `rfc_factura` VARCHAR(255) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_factura`, `compras_id_compra`, `usuario_id_usuario`),
  INDEX `fk_factura_compras1_idx` (`compras_id_compra` ASC),
  INDEX `fk_factura_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_factura_compras1`
    FOREIGN KEY (`compras_id_compra`)
    REFERENCES `mydb`.`compras` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evento_en_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento_en_carrito` (
  `carrito_id_carrito` INT NOT NULL,
  `evento_id_evento` INT NOT NULL,
  PRIMARY KEY (`carrito_id_carrito`, `evento_id_evento`),
  INDEX `fk_evento_en_carrito_evento1_idx` (`evento_id_evento` ASC),
  CONSTRAINT `fk_evento_en_carrito_carrito1`
    FOREIGN KEY (`carrito_id_carrito`)
    REFERENCES `mydb`.`carrito` (`id_carrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_en_carrito_evento1`
    FOREIGN KEY (`evento_id_evento`)
    REFERENCES `mydb`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`costos_adicionales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`costos_adicionales` (
  `id_costo` INT NOT NULL,
  `nombre_costo` VARCHAR(255) NOT NULL,
  `costo` INT NOT NULL,
  `estado_id_estado` INT NOT NULL,
  PRIMARY KEY (`id_costo`, `estado_id_estado`),
  INDEX `fk_costos_adicionales_estado1_idx` (`estado_id_estado` ASC),
  CONSTRAINT `fk_costos_adicionales_estado1`
    FOREIGN KEY (`estado_id_estado`)
    REFERENCES `mydb`.`estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos_compra` (
  `productos_id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `compras_id_compra` INT NOT NULL,
  PRIMARY KEY (`productos_id_producto`, `compras_id_compra`),
  INDEX `fk_eventos_compra_compras1_idx` (`compras_id_compra` ASC),
  CONSTRAINT `fk_eventos_compra_productos1`
    FOREIGN KEY (`productos_id_producto`)
    REFERENCES `mydb`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_compra_compras1`
    FOREIGN KEY (`compras_id_compra`)
    REFERENCES `mydb`.`compras` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eventos_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eventos_compra` (
  `evento_id_evento` INT NOT NULL,
  `compras_id_compra` INT NOT NULL,
  PRIMARY KEY (`evento_id_evento`, `compras_id_compra`),
  INDEX `fk_eventos_compra_compras2_idx` (`compras_id_compra` ASC),
  CONSTRAINT `fk_eventos_compra_evento1`
    FOREIGN KEY (`evento_id_evento`)
    REFERENCES `mydb`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_compra_compras2`
    FOREIGN KEY (`compras_id_compra`)
    REFERENCES `mydb`.`compras` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participantes_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participantes_evento` (
  `evento_id_evento` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`evento_id_evento`, `usuario_id_usuario`),
  INDEX `fk_participantes_evento_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_participantes_evento_evento1`
    FOREIGN KEY (`evento_id_evento`)
    REFERENCES `mydb`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participantes_evento_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
